name: Build RSS feed from Releases

on:
  schedule:
    - cron: '0 0 * * *'     # 每天 00:00 UTC 运行（UTC+8=08:00，本地早8点自动更新）
  release:
    types: [published]       # 发布 Release 时自动运行
  workflow_dispatch:         # 需要时可手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PODCAST_TITLE: "我的论文播客"
      PODCAST_LINK: "https://<你的用户名>.github.io/sci-podcast/"
      PODCAST_DESCRIPTION: "每天自动生成的论文摘要播客"
    steps:
      - uses: actions/checkout@v4

      - name: Generate feed.xml from releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          mkdir -p docs
          python - <<'PY'
          import os, requests, datetime, email.utils, html
          owner_repo = os.getenv("REPO")  # e.g. user/repo
          token = os.getenv("GH_TOKEN")
          title = os.getenv("PODCAST_TITLE")
          link = os.getenv("PODCAST_LINK")
          desc = os.getenv("PODCAST_DESCRIPTION")

          s = requests.Session()
          s.headers.update({
              "Authorization": f"Bearer {token}",
              "Accept": "application/vnd.github+json",
              "X-GitHub-Api-Version": "2022-11-28"
          })

          releases, page = [], 1
          while True:
              r = s.get(f"https://api.github.com/repos/{owner_repo}/releases",
                        params={"per_page":100, "page":page})
              r.raise_for_status()
              data = r.json()
              if not data: break
              releases.extend(data); page += 1

          items = []
          for rel in releases:
              pub = rel.get("published_at") or rel.get("created_at")
              dt = datetime.datetime.fromisoformat(pub.replace("Z","+00:00"))
              pubDate = email.utils.format_datetime(dt)
              rel_name = rel.get("name") or rel.get("tag_name") or "Episode"
              for a in rel.get("assets", []):
                  name = (a.get("name") or "")
                  if not name.lower().endswith(".mp3"): 
                      continue
                  url = a.get("browser_download_url")
                  length = a.get("size") or 0
                  guid = f"{rel.get('tag_name')}-{a.get('id')}"
                  items.append({
                      "title": f"{rel_name} · {name}",
                      "url": url,
                      "length": str(length),
                      "guid": guid,
                      "pubDate": pubDate
                  })

          lines = []
          lines.append('<?xml version="1.0" encoding="UTF-8" ?>')
          lines.append('<rss version="2.0">')
          lines.append('  <channel>')
          lines.append(f'    <title>{html.escape(title)}</title>')
          lines.append(f'    <link>{html.escape(link)}</link>')
          lines.append(f'    <description>{html.escape(desc)}</description>')
          lines.append('    <language>en-us</language>')
          for it in sorted(items, key=lambda x: x["pubDate"], reverse=True):
              lines.append('    <item>')
              lines.append(f'      <title>{html.escape(it["title"])}</title>')
              lines.append(f'      <enclosure url="{html.escape(it["url"])}" length="{it["length"]}" type="audio/mpeg"/>')
              lines.append(f'      <guid>{html.escape(it["guid"])}</guid>')
              lines.append(f'      <pubDate>{it["pubDate"]}</pubDate>')
              lines.append('    </item>')
          lines.append('  </channel>')
          lines.append('</rss>')
          with open("docs/feed.xml","w",encoding="utf-8") as f:
              f.write("\n".join(lines))
          print("feed.xml created.")
          PY

      - name: Commit & push feed.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update feed.xml"
          file_pattern: docs/feed.xml
