name: TTS from posts

on:
  workflow_dispatch:

# ✅ 防并发：同一分支只保留最新一次运行，取消在途运行，避免触发 429
concurrency:
  group: tts-from-posts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cognitiveservices-speech pydub
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Verify Azure secrets
        run: |
          test -n "${{ secrets.SPEECH_KEY }}" || (echo "Missing SPEECH_KEY" && exit 1)
          test -n "${{ secrets.SPEECH_REGION }}" || (echo "Missing SPEECH_REGION" && exit 1)

      - name: Debug posts folder
        run: |
          echo "Listing posts/"
          ls -alh posts || echo "No posts folder!"
          echo "Show first file head (if any):"
          for f in posts/*.txt; do
            [ -e "$f" ] || continue
            echo "---- $f ----"
            head -n 5 "$f"
            break
          done

      # ✅ 强节流 + 混合声线（Host=Emma HD，Scientist=Andrew Multilingual）
      - name: Run TTS batch (heavy throttling)
        env:
          SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
          SPEECH_REGION: ${{ secrets.SPEECH_REGION }}

          VOICE_HOST: en-US-Emma:DragonHDLatestNeural
          VOICE_SCI:  en-US-AndrewMultilingualNeural

          # 速率仅对 Multilingual 生效（HD 不支持 <prosody>）
          SPEED: +20%

          # ↓↓↓ 全局节流参数（和我给你的 tts_batch.py 对应）
          THROTTLE_MS: "8000"        # 每块间隔 7s
          CHUNK_PAUSE_EVERY: "3"     # 每 3 块长休眠
          CHUNK_PAUSE_SECS: "45"     # 长休眠 35s
          RETRIES: "14"              # 每块重试上限

        run: |
          # 尽量减少请求数（块更少）→ 降 429 概率；文本很长就适当调低
          python tts_batch.py --merge --max-chars 3600 --max-sents 120 --break-ms 300 --only-full-to-docs
          echo "List outputs:"
          ls -alh tts_out || true
          ls -alh docs/audio || true

      - name: Commit merged audio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/audio
          git commit -m "Add merged TTS outputs" || echo "Nothing to commit"
          git push
