name: TTS from posts

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cognitiveservices-speech

      - name: Run TTS batch
        env:
          SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
          SPEECH_REGION: ${{ secrets.SPEECH_REGION }}
          VOICE_HOST: en-US-EmmaDragonHDLatestNeural
          VOICE_SCI: en-US-AndrewMultilingualNeural
          SPEED: 20%
        run: |
          python tts_batch.py --merge --only-full-to-docs

      - name: Commit merged TTS outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/audio
          git commit -m "Add merged TTS outputs" || echo "Nothing to commit"
          git push
