name: TTS from posts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cognitiveservices-speech pydub

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq

      - name: Verify Azure secrets
        run: |
          test -n "${{ secrets.SPEECH_KEY }}" || (echo "Missing SPEECH_KEY" && exit 1)
          test -n "${{ secrets.SPEECH_REGION }}" || (echo "Missing SPEECH_REGION" && exit 1)

      # 可选但强烈建议：检查你选的 voice 是否在该 region 可用
      - name: Check voices availability
        env:
          SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
          SPEECH_REGION: ${{ secrets.SPEECH_REGION }}
        run: |
          set -e
          curl -sS -f -H "Ocp-Apim-Subscription-Key: ${SPEECH_KEY}" \
            "https://${SPEECH_REGION}.tts.speech.microsoft.com/cognitiveservices/voices/list" > voices.json
          echo "Top voices in ${SPEECH_REGION}:"
          cat voices.json | jq -r '.[0:8][] | "\(.ShortName) | \(.Locale)"'
          (cat voices.json | jq -r '.[].ShortName' | grep -x "en-US-EmmaMultilingualNeural") || (echo "Voice en-US-EmmaMultilingualNeural not available in ${SPEECH_REGION}" && exit 1)
          (cat voices.json | jq -r '.[].ShortName' | grep -x "en-US-AndrewMultilingualNeural") || (echo "Voice en-US-AndrewMultilingualNeural not available in ${SPEECH_REGION}" && exit 1)
          echo "Both voices available."

      - name: Debug posts folder
        run: |
          echo "Listing posts/"
          ls -alh posts || echo "No posts folder!"
          echo "Show first file head (if any):"
          for f in posts/*.txt; do
            [ -e "$f" ] || continue
            echo "---- $f ----"
            head -n 5 "$f"
            break
          done

      - name: Run TTS batch
        env:
          SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
          SPEECH_REGION: ${{ secrets.SPEECH_REGION }}
          VOICE_HOST: en-US-EmmaMultilingualNeural
          VOICE_SCI: en-US-AndrewMultilingualNeural
          SPEED: +20%   # ← 关键修复：必须带“+”
        run: |
          python tts_batch.py --merge --only-full-to-docs
          echo "List outputs:"
          ls -alh tts_out || true
          ls -alh docs/audio || true

      - name: Commit merged audio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/audio
          git commit -m "Add merged TTS outputs" || echo "Nothing to commit"
          git push
